version: '3.8'

services:
  db:
    image: mysql:5.7  # Using 5.7 as an example, you can use latest or any other version you prefer
    environment:
      MYSQL_DATABASE: 'd2ld_db'
      MYSQL_USER: 'd2ld_admin'
      MYSQL_PASSWORD: 'df23fwe'
      MYSQL_ROOT_PASSWORD: 'df23fwe'
    volumes:
      - d2ld-db-data:/var/lib/mysql
    ports:
      - '779:3306'
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'  # Use this line if your MySQL client has auth issues.

  backend:
    build:
      context: ./d2ld-backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=d2ld_admin
      - DB_PASSWORD=df23fwe
      - DB_NAME=d2ld_db
    ports:
      - '778:3000'
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: ./d2ld-frontend
      dockerfile: Dockerfile
    ports:
      - '777:80'
    restart: always
    depends_on:
      - backend

volumes:
  d2ld-db-data:

networks:
  default:
    driver: bridge
